# This file is auto-generated by scripts/gen_stubs.py — do not edit manually.
# Run `uv run python scripts/gen_stubs.py` to regenerate.

from collections.abc import Iterator as Iterator
from typing import Literal as Literal

from ..data import Data as Data
from ._concat_aggregate import ConcatAggregate as ConcatAggregate
from ._mean_aggregate import MeanAggregate as MeanAggregate
from ._sliding_window import SlidingWindow as SlidingWindow
from ._sliding_window_reduce import SlidingWindowReduce as SlidingWindowReduce

def sliding_window(data: Data, window_size: int = ..., step_size: int = ...) -> Iterator[Data]: ...
def sliding_window_reduce(
    data: Data,
    window_size: int = ...,
    step_size: int = ...,
    dim: str = ...,
    agg: Literal["mean", "std", "sum", "min", "max"] = ...,
) -> Data: ...

__all__ = [
    "ConcatAggregate",
    "MeanAggregate",
    "SlidingWindow",
    "SlidingWindowReduce",
    "sliding_window",
    "sliding_window_reduce",
]
