minimum_pre_commit_version: "4.5.0"

repos:
- repo: local
  hooks:
    - id: gen-feature-stubs
      name: generate feature stubs
      entry: uv run python scripts/gen_stubs.py
      language: system
      pass_filenames: false
      files: ^src/cobrabox/features/.*\.py$

    - id: ty-check
      name: ty check
      entry: uv run ty check src
      language: system
      pass_filenames: false

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.5
  hooks:
    # ruff linter - on par with `uvx ruff check`
    - id: ruff-check
    # ruff formatter - on par with `uvx ruff format`
    - id: ruff-format

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.10.9
  hooks:
    # run uv lock and upgrade - on par with `uv lock && uv lock --upgrade`
    - id: uv-lock
      args: [--upgrade]
