# This file is auto-generated by scripts/gen_stubs.py — do not edit manually.
# Run `uv run python scripts/gen_stubs.py` to regenerate.

from typing import Literal as Literal

from ..data import Data as Data
from ._amplitude_entropy import AmplitudeEntropy as AmplitudeEntropy
from ._fractal_dimension import FractalDimension as FractalDimension
from ._lempel_ziv import LempelZiv as LempelZiv
from ._nonreversibility import Nonreversibility as Nonreversibility
from ._recurrence_matrix import RecMetric as RecMetric
from ._recurrence_matrix import RecurrenceMatrix as RecurrenceMatrix
from ._sample_entropy import SampleEntropy as SampleEntropy

def amplitude_entropy(data: Data, band_width: float) -> Data: ...
def fractal_dimension(
    data: Data, method: Literal["higuchi", "katz"] = ..., k_max: int = ...
) -> Data: ...
def lempel_ziv(data: Data) -> Data: ...
def nonreversibility(data: Data) -> Data: ...
def recurrence_matrix(
    data: Data, rec_metric: RecMetric = ..., fc_options: list[str | int | float] = ...
) -> Data: ...
def sample_entropy(
    data: Data, m: int = ..., r: float | None = ..., log_base: float = ...
) -> Data: ...

__all__ = [
    "AmplitudeEntropy",
    "FractalDimension",
    "LempelZiv",
    "Nonreversibility",
    "RecurrenceMatrix",
    "SampleEntropy",
    "amplitude_entropy",
    "fractal_dimension",
    "lempel_ziv",
    "nonreversibility",
    "recurrence_matrix",
    "sample_entropy",
]
