# This file is auto-generated by scripts/gen_stubs.py — do not edit manually.
# Run `uv run python scripts/gen_stubs.py` to regenerate.

from typing import Literal as Literal

import xarray as xr

from ..data import Data as Data
from ._emd import EMD as EMD
from ._svd import SVD as SVD
from ._svd import _SVDOutputMode as _SVDOutputMode

def emd(
    data: Data,
    max_imfs: int | None = ...,
    method: Literal["sift", "mask_sift", "iterated_mask_sift"] = ...,
    keep_orig: bool = ...,
) -> Data: ...
def svd(
    data: Data,
    dim: str,
    n_components: int = ...,
    center: bool = ...,
    zscore: bool = ...,
    mask: xr.DataArray | None = ...,
    return_unstacked_V: bool = ...,
    output: _SVDOutputMode = ...,
) -> Data: ...

__all__ = ["EMD", "SVD", "emd", "svd"]
