# This file is auto-generated by scripts/gen_stubs.py — do not edit manually.
# Run `uv run python scripts/gen_stubs.py` to regenerate.

from ..data import Data as Data
from ._coherence import Coherence as Coherence
from ._correlation import Correlation as Correlation
from ._covariance import Covariance as Covariance
from ._directed_transfer_function import DirectedTransferFunction as DirectedTransferFunction
from ._envelope_correlation import EnvelopeCorrelation as EnvelopeCorrelation
from ._granger_causality import GrangerCausality as GrangerCausality
from ._mutual_information import MutualInformation as MutualInformation
from ._partial_correlation import PartialCorrelation as PartialCorrelation
from ._partial_directed_coherence import PartialDirectedCoherence as PartialDirectedCoherence
from ._phase_locking_value import PhaseLockingValue as PhaseLockingValue
from ._reciprocal_connectivity import ReciprocalConnectivity as ReciprocalConnectivity

def coherence(data: Data, nperseg: int | None = ...) -> Data: ...
def correlation(data: Data, dim: str = ..., method: str = ...) -> Data: ...
def covariance(data: Data, dim: str = ...) -> Data: ...
def directed_transfer_function(
    data: Data, var_order: int | None = ..., n_freqs: int = ...
) -> Data: ...
def envelope_correlation(
    data: Data, orthogonalize: str | bool = ..., absolute: bool = ...
) -> Data: ...
def granger_causality(
    data: Data, coords: list[str] | list[int] | None = ..., lag: int | None = ..., maxlag: int = ...
) -> Data: ...
def mutual_information(
    data: Data,
    dim: str = ...,
    other_dim: str | None = ...,
    bins: int | None = ...,
    equiprobable_bins: bool = ...,
    log_base: float = ...,
) -> Data: ...
def partial_correlation(
    data: Data,
    coords: list[str] | list[int] | None = ...,
    control_vars: list[str] | list[int] | None = ...,
) -> Data: ...
def partial_directed_coherence(
    data: Data, var_order: int | None = ..., n_freqs: int = ...
) -> Data: ...
def phase_locking_value(data: Data, coords: list[str] | list[int] | None = ...) -> Data: ...
def reciprocal_connectivity(
    data: Data, freq_band: tuple[float, float] | None = ..., normalize: bool = ...
) -> Data: ...

__all__ = [
    "Coherence",
    "Correlation",
    "Covariance",
    "DirectedTransferFunction",
    "EnvelopeCorrelation",
    "GrangerCausality",
    "MutualInformation",
    "PartialCorrelation",
    "PartialDirectedCoherence",
    "PhaseLockingValue",
    "ReciprocalConnectivity",
    "coherence",
    "correlation",
    "covariance",
    "directed_transfer_function",
    "envelope_correlation",
    "granger_causality",
    "mutual_information",
    "partial_correlation",
    "partial_directed_coherence",
    "phase_locking_value",
    "reciprocal_connectivity",
]
