# This file is auto-generated by scripts/gen_stubs.py — do not edit manually.
# Run `uv run python scripts/gen_stubs.py` to regenerate.

from ..data import Data as Data
from ._amplitude_variation import AmplitudeVariation as AmplitudeVariation
from ._autocorrelation import Autocorrelation as Autocorrelation
from ._epileptogenicity_index import EpileptogenicityIndex as EpileptogenicityIndex
from ._line_length import LineLength as LineLength
from ._max import Max as Max
from ._mean import Mean as Mean
from ._min import Min as Min
from ._spike_count import SpikeCount as SpikeCount

def amplitude_variation(data: Data) -> Data: ...
def autocorrelation(
    data: Data, dim: str, fs: float, lag_steps: int | None = ..., lag_ms: float | None = ...
) -> Data: ...
def epileptogenicity_index(
    data: Data,
    window_duration: float = ...,
    bias: float = ...,
    threshold: float = ...,
    integration_window: float = ...,
    tau: float = ...,
) -> Data: ...
def line_length(data: Data) -> Data: ...
def max(data: Data, dim: str) -> Data: ...
def mean(data: Data, dim: str) -> Data: ...
def min(data: Data, dim: str) -> Data: ...
def spike_count(data: Data) -> Data: ...

__all__ = [
    "AmplitudeVariation",
    "Autocorrelation",
    "EpileptogenicityIndex",
    "LineLength",
    "Max",
    "Mean",
    "Min",
    "SpikeCount",
    "amplitude_variation",
    "autocorrelation",
    "epileptogenicity_index",
    "line_length",
    "max",
    "mean",
    "min",
    "spike_count",
]
