# This file is auto-generated by scripts/gen_stubs.py — do not edit manually.
# Run `uv run python scripts/gen_stubs.py` to regenerate.

from typing import Literal as Literal

from ..data import Data as Data
from ._analytic_signal import AnalyticSignal as AnalyticSignal
from ._bandpass_filter import BandpassFilter as BandpassFilter
from ._fourier_transform import FourierTransform as FourierTransform
from ._inverse_fourier_transform import InverseFourierTransform as InverseFourierTransform

def analytic_signal(
    data: Data, feature: Literal["analytic", "envelope", "phase", "frequency"] = ...
) -> Data: ...
def bandpass_filter(
    data: Data, bands: dict[str, list[float]] = ..., ord: int = ..., keep_orig: bool = ...
) -> Data: ...
def fourier_transform(data: Data, return_magnitude: bool = ...) -> Data: ...
def inverse_fourier_transform(
    data: Data, n: int | None = ..., sampling_rate: float | None = ...
) -> Data: ...

__all__ = [
    "AnalyticSignal",
    "BandpassFilter",
    "FourierTransform",
    "InverseFourierTransform",
    "analytic_signal",
    "bandpass_filter",
    "fourier_transform",
    "inverse_fourier_transform",
]
