#!/usr/bin/env python3
"""Generate src/cobrabox/features/__init__.pyi from discovered feature classes.

Scans every .py file in the features package (excluding __init__.py) using AST,
finds all classes that inherit directly from BaseFeature, SplitterFeature, or
AggregatorFeature (with or without type-parameter subscript), and writes a stub
file with explicit re-exports so IDEs and type checkers can resolve them.

Exit codes:
  0 — stub is already up to date
  1 — stub was updated (pre-commit will re-stage the file)
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

BASE_CLASSES = {"BaseFeature", "SplitterFeature", "AggregatorFeature"}

REPO_ROOT = Path(__file__).parent.parent
FEATURES_DIR = REPO_ROOT / "src" / "cobrabox" / "features"
STUB_PATH = FEATURES_DIR / "__init__.pyi"

HEADER = """\
# This file is auto-generated by scripts/gen_stubs.py — do not edit manually.
# Run `uv run python scripts/gen_stubs.py` to regenerate.
"""


def _base_name(node: ast.expr) -> str | None:
    """Return the base-class name from a Name or Subscript node."""
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name):
        return node.value.id
    return None


def find_feature_classes(path: Path) -> list[str]:
    """Return sorted list of feature class names defined in *path*."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    names = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            bases = {_base_name(b) for b in node.bases}
            if bases & BASE_CLASSES:
                names.append(node.name)
    return sorted(names)


def generate_stub() -> str:
    modules = sorted(p for p in FEATURES_DIR.glob("*.py") if p.name != "__init__.py")

    lines: list[str] = [HEADER]
    all_names: list[str] = []

    for module_path in modules:
        classes = find_feature_classes(module_path)
        if not classes:
            continue
        stem = module_path.stem
        for cls in classes:
            lines.append(f"from .{stem} import {cls} as {cls}\n")
            all_names.append(cls)

    lines.append("\n__all__ = [\n")
    for name in sorted(all_names):
        lines.append(f'    "{name}",\n')
    lines.append("]\n")

    return "".join(lines)


def main() -> int:
    stub = generate_stub()
    current = STUB_PATH.read_text(encoding="utf-8") if STUB_PATH.exists() else ""
    if stub == current:
        return 0
    STUB_PATH.write_text(stub, encoding="utf-8")
    print(f"Updated {STUB_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
