#!/usr/bin/env python3
"""Generate the ``cb.feature`` stub for IDE / type-checker support.

``cb.feature`` is populated dynamically (``feature.py`` scans the domain packages
and ``globals().update()``s the result), so static analysis cannot see its
members. This writes ``src/cobrabox/feature.pyi`` re-exporting every feature — the
class ``Correlation`` and its one-shot function ``correlation`` alike — from the
private module each lives in.

The functions themselves are ordinary static defs in the feature files (see
``_functional.py``), so ``cb.correlation`` and ``cb.connectivity.correlation``
need no stub — only the dynamic ``cb.feature`` namespace does.

Exit codes:
  0 — stub is already up to date
  1 — stub was updated (pre-commit will re-stage the file)
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

BASE_CLASSES = {"BaseFeature", "SplitterFeature", "AggregatorFeature"}

REPO_ROOT = Path(__file__).parent.parent
PACKAGE_ROOT = REPO_ROOT / "src" / "cobrabox"
FEATURE_STUB_PATH = PACKAGE_ROOT / "feature.pyi"

DOMAIN_BLOCKLIST = {"egg", "__pycache__"}

HEADER_FEATURE = """\
# This file is auto-generated by scripts/gen_stubs.py — do not edit manually.
# Run `uv run python scripts/gen_stubs.py` to regenerate.
# ruff: noqa: RUF022
"""


def _base_name(node: ast.expr) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name):
        return node.value.id
    return None


def _has_functional_decorator(node: ast.FunctionDef) -> bool:
    """True if the function is decorated with ``@functional(...)``."""
    for dec in node.decorator_list:
        target = dec.func if isinstance(dec, ast.Call) else dec
        if isinstance(target, ast.Name) and target.id == "functional":
            return True
    return False


def find_feature_symbols(path: Path) -> list[str]:
    """Feature classes and their ``@functional`` wrapper functions in one module."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    names: list[str] = []
    for node in tree.body:  # module level only
        if isinstance(node, ast.ClassDef) and {_base_name(b) for b in node.bases} & BASE_CLASSES:
            names.append(node.name)
        elif isinstance(node, ast.FunctionDef) and _has_functional_decorator(node):
            names.append(node.name)
    return sorted(names)


def _collect_symbols() -> dict[str, list[str]]:
    """{relative_module_path: [Name, ...]} across every domain."""
    result: dict[str, list[str]] = {}
    for domain_dir in sorted(PACKAGE_ROOT.iterdir()):
        if not domain_dir.is_dir():
            continue
        if domain_dir.name in DOMAIN_BLOCKLIST or domain_dir.name.startswith("_"):
            continue
        for module_path in sorted(domain_dir.rglob("*.py")):
            # Implementation modules are private (`_autocorrelation.py`), so `_*.py`
            # is scanned rather than skipped. Files with no feature — e.g.
            # `connectivity/_mvar.py` — simply contribute nothing.
            if module_path.name == "__init__.py":
                continue
            rel_path = module_path.relative_to(PACKAGE_ROOT)
            module_key = "/".join(rel_path.with_suffix("").parts)
            symbols = find_feature_symbols(module_path)
            if symbols:
                result[module_key] = symbols
    return result


def _all_block(names: list[str]) -> str:
    items = "".join(f'    "{n}",\n' for n in sorted(names, key=str.casefold))
    return f"\n__all__ = [\n{items}]\n"


def _split_import_line(import_path: str, name: str) -> str:
    line = f"from {import_path} import {name} as {name}"
    # Match ruff's line-length check, which measures the line without its newline.
    if len(line.encode("utf-8")) <= 100:
        return line + "\n"
    return f"from {import_path} import (\n    {name} as {name},\n)\n"


def generate_feature_stub(symbols_by_module: dict[str, list[str]]) -> str:
    all_names = sorted(
        (n for symbols in symbols_by_module.values() for n in symbols), key=str.casefold
    )
    lines: list[str] = [HEADER_FEATURE]
    for module_path, symbols in symbols_by_module.items():
        import_path = f".{module_path.replace('/', '.')}"
        for name in symbols:
            lines.append(_split_import_line(import_path, name))
    lines.append(_all_block(all_names))
    return "".join(lines)


def _write_if_changed(path: Path, content: str) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if content == current:
        return False
    path.write_text(content, encoding="utf-8")
    print(f"Updated {path.relative_to(REPO_ROOT)}", file=sys.stderr)
    return True


def main() -> int:
    changed = _write_if_changed(FEATURE_STUB_PATH, generate_feature_stub(_collect_symbols()))
    return 1 if changed else 0


if __name__ == "__main__":
    sys.exit(main())
