#!/usr/bin/env python3
"""Generate feature stubs for IDE / type-checker support.

Scans every domain subdirectory of ``src/cobrabox/`` (skipping ``egg/`` and
``_*``), finds classes inheriting from BaseFeature / SplitterFeature /
AggregatorFeature, and writes a stub at::

  src/cobrabox/feature.pyi    — for ``cb.feature.X``

Exit codes:
  0 — stub is already up to date
  1 — stub was updated (pre-commit will re-stage the file)
"""

from __future__ import annotations

import ast
import subprocess
import sys
from pathlib import Path

BASE_CLASSES = {"BaseFeature", "SplitterFeature", "AggregatorFeature"}

REPO_ROOT = Path(__file__).parent.parent
PACKAGE_ROOT = REPO_ROOT / "src" / "cobrabox"
FEATURE_STUB_PATH = PACKAGE_ROOT / "feature.pyi"

DOMAIN_BLOCKLIST = {"egg", "__pycache__"}

HEADER_FEATURE = """\
# This file is auto-generated by scripts/gen_stubs.py — do not edit manually.
# Run `uv run python scripts/gen_stubs.py` to regenerate.
# ruff: noqa: RUF022
"""


def _base_name(node: ast.expr) -> str | None:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Subscript) and isinstance(node.value, ast.Name):
        return node.value.id
    return None


def find_feature_classes(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    names: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            bases = {_base_name(b) for b in node.bases}
            if bases & BASE_CLASSES:
                names.append(node.name)
    return sorted(names)


def _collect_classes() -> dict[str, list[str]]:
    """{relative_module_path: [ClassName, ...]} across every domain."""
    result: dict[str, list[str]] = {}
    for domain_dir in sorted(PACKAGE_ROOT.iterdir()):
        if not domain_dir.is_dir():
            continue
        if domain_dir.name in DOMAIN_BLOCKLIST or domain_dir.name.startswith("_"):
            continue
        for module_path in sorted(domain_dir.rglob("*.py")):
            # Implementation modules are private (`_autocorrelation.py`), so `_*.py`
            # is scanned rather than skipped. Files with no feature class — e.g.
            # `connectivity/_mvar.py` — simply contribute nothing.
            if module_path.name == "__init__.py":
                continue
            rel_path = module_path.relative_to(PACKAGE_ROOT)
            module_key = "/".join(rel_path.with_suffix("").parts)
            classes = find_feature_classes(module_path)
            if classes:
                result[module_key] = classes
    return result


def _all_block(names: list[str]) -> str:
    items = "".join(f'    "{n}",\n' for n in sorted(names))
    return f"\n__all__ = [\n{items}]\n"


def _split_import_line(import_path: str, cls: str) -> str:
    line = f"from {import_path} import {cls} as {cls}"
    # Match ruff's line-length check, which measures the line without its newline.
    if len(line.encode("utf-8")) <= 100:
        return line + "\n"
    return f"from {import_path} import (\n    {cls} as {cls},\n)\n"


def generate_feature_stub(classes_by_module: dict[str, list[str]]) -> str:
    all_names = sorted(
        (cls for classes in classes_by_module.values() for cls in classes), key=str.casefold
    )
    lines: list[str] = [HEADER_FEATURE]
    for module_path, classes in classes_by_module.items():
        import_path = f".{module_path.replace('/', '.')}"
        for cls in classes:
            lines.append(_split_import_line(import_path, cls))
    lines.append(_all_block(all_names))
    return "".join(lines)


def _ruff_format(content: str, path: Path) -> str:
    """Format generated source with ruff so the output is stable across runs.

    Without this the generator emits one long `def` per feature and the formatter
    rewraps it, so `gen_stubs.py` and `ruff format` would fight: each would report
    the file as changed after the other ran. `--stdin-filename` gives ruff the
    `.pyi` extension it needs to apply stub style.
    """
    try:
        proc = subprocess.run(
            ["ruff", "format", "--stdin-filename", str(path), "-"],
            input=content,
            capture_output=True,
            text=True,
            check=True,
        )
    except OSError, subprocess.CalledProcessError:
        # ruff missing or unhappy — emit unformatted rather than failing the build.
        return content
    return proc.stdout


def _write_if_changed(path: Path, content: str) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    if content == current:
        return False
    path.write_text(content, encoding="utf-8")
    print(f"Updated {path.relative_to(REPO_ROOT)}", file=sys.stderr)
    return True


# ─── Functional API stubs (GH #116) ───────────────────────────────────────────
#
# The one-shot wrappers (`cb.line_length(d)`) are built at import time by
# `_functional.install`, so type-checkers cannot see them. Emit a `.pyi` per
# domain package declaring both forms.

HEADER_DOMAIN = """\
# This file is auto-generated by scripts/gen_stubs.py — do not edit manually.
# Run `uv run python scripts/gen_stubs.py` to regenerate.
"""

# Annotations are copied verbatim from the source, so the stub must import every
# name they mention. Builtins need nothing; these are the module aliases feature
# files use. Anything else is resolved against the implementation module it came
# from (e.g. `_SVDOutputMode` in `_svd.py`).
_STUB_BUILTINS = frozenset(
    {"int", "str", "float", "bool", "None", "list", "dict", "tuple", "set", "bytes", "object"}
)
_STUB_KNOWN_IMPORTS = {
    "Literal": "from typing import Literal as Literal",
    "Any": "from typing import Any as Any",
    "np": "import numpy as np",
    "xr": "import xarray as xr",
}


def _annotation_names(annotation: str) -> set[str]:
    """Top-level identifiers referenced by an annotation string."""
    try:
        tree = ast.parse(annotation, mode="eval")
    except SyntaxError:
        return set()
    names = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Name):
            names.add(node.id)
    return names - _STUB_BUILTINS


def _functional_signature(cls: type, fn_name: str) -> str:
    """`def line_length(data: Data, dim: str = ...) -> Data: ...`

    Annotations are taken verbatim from the source. Every feature file uses
    `from __future__ import annotations`, so `field.type` is already the
    annotation *string* and needs no rendering.
    """
    import dataclasses

    parts = ["data: Data"]
    for f in dataclasses.fields(cls):
        if not f.init or f.name.startswith("_"):
            continue
        annotation = f.type if isinstance(f.type, str) else getattr(f.type, "__name__", "Any")
        optional = (
            f.default is not dataclasses.MISSING or f.default_factory is not dataclasses.MISSING  # type: ignore[misc]
        )
        parts.append(f"{f.name}: {annotation}" + (" = ..." if optional else ""))
    returns = "Iterator[Data]" if _is_splitter(cls) else "Data"
    return f"def {fn_name}({', '.join(parts)}) -> {returns}: ..."


def _is_splitter(cls: type) -> bool:
    from cobrabox.base_feature import SplitterFeature

    return issubclass(cls, SplitterFeature)


def _annotations_of(cls: type) -> list[str]:
    import dataclasses

    return [
        f.type
        for f in dataclasses.fields(cls)
        if f.init and not f.name.startswith("_") and isinstance(f.type, str)
    ]


def generate_domain_stubs() -> list[tuple[Path, str]]:
    """One `.pyi` per domain, declaring the classes and the functional wrappers."""
    import importlib

    from cobrabox._functional import function_name, has_functional_form

    stubs: list[tuple[Path, str]] = []
    for domain_dir in sorted(PACKAGE_ROOT.iterdir()):
        if not domain_dir.is_dir() or domain_dir.name in DOMAIN_BLOCKLIST:
            continue
        if domain_dir.name.startswith("_") or not (domain_dir / "__init__.py").exists():
            continue
        module = importlib.import_module(f"cobrabox.{domain_dir.name}")
        classes = [
            getattr(module, n) for n in module.__all__ if isinstance(getattr(module, n, None), type)
        ]
        if not classes:
            continue

        # Signatures first: they determine which supporting names must be imported.
        signatures: list[str] = []
        extra_imports: set[str] = set()
        exported = [c.__name__ for c in classes]
        for cls in classes:
            if not has_functional_form(cls):
                continue
            fn_name = function_name(cls)
            signatures.append(_functional_signature(cls, fn_name))
            exported.append(fn_name)
            impl_module = importlib.import_module(cls.__module__)
            impl = cls.__module__.rsplit(".", 1)[-1]
            for annotation in _annotations_of(cls):
                for ref in _annotation_names(annotation):
                    if ref in _STUB_KNOWN_IMPORTS:
                        extra_imports.add(_STUB_KNOWN_IMPORTS[ref])
                    elif hasattr(impl_module, ref):
                        extra_imports.add(f"from .{impl} import {ref} as {ref}")

        # isort order: stdlib, third-party, then local — so the stub needs no noqa.
        stdlib = {i for i in extra_imports if i.startswith(("from typing", "from collections"))}
        third_party = {i for i in extra_imports if i.startswith("import ")}
        local = extra_imports - stdlib - third_party
        if any(_is_splitter(c) for c in classes):
            stdlib.add("from collections.abc import Iterator as Iterator")
        local.add("from ..data import Data as Data")
        for cls in classes:
            impl = cls.__module__.rsplit(".", 1)[-1]
            local.add(f"from .{impl} import {cls.__name__} as {cls.__name__}")

        lines = [HEADER_DOMAIN]
        for group in (stdlib, third_party, local):
            if not group:
                continue
            lines.append("\n")  # isort separates the groups with a blank line
            lines.extend(f"{line}\n" for line in sorted(group))
        lines.append("\n")
        lines.extend(f"{sig}\n" for sig in signatures)
        lines.append(_all_block(exported))
        stubs.append((domain_dir / "__init__.pyi", "".join(lines)))
    return stubs


def main() -> int:
    classes_by_module = _collect_classes()
    changed = _write_if_changed(FEATURE_STUB_PATH, generate_feature_stub(classes_by_module))
    for path, content in generate_domain_stubs():
        changed |= _write_if_changed(path, _ruff_format(content, path))
    return 1 if changed else 0


if __name__ == "__main__":
    sys.exit(main())
