# This file is auto-generated by scripts/gen_stubs.py — do not edit manually.
# Run `uv run python scripts/gen_stubs.py` to regenerate.

from typing import Literal as Literal

from ..data import Data as Data
from ._band_power import BandPower as BandPower
from ._continuous_wavelet_transform import ContinuousWaveletTransform as ContinuousWaveletTransform
from ._continuous_wavelet_transform import _CwtWavelet as _CwtWavelet
from ._cordance import Cordance as Cordance
from ._discrete_wavelet_transform import DiscreteWaveletTransform as DiscreteWaveletTransform
from ._discrete_wavelet_transform import _DwtWavelet as _DwtWavelet
from ._spectrogram import Spectrogram as Spectrogram

def band_power(
    data: Data, bands: dict[str, list[float] | bool] | None = ..., nperseg: int | None = ...
) -> Data: ...
def continuous_wavelet_transform(
    data: Data,
    wavelet: _CwtWavelet = ...,
    scales: list[float] | None = ...,
    n_scales: int = ...,
    scaling: Literal["magnitude", "power", "complex"] = ...,
) -> Data: ...
def cordance(
    data: Data,
    bands: dict[str, list[float] | bool] | None = ...,
    nperseg: int | None = ...,
    threshold: float = ...,
    output: Literal["cordance", "concordance", "discordance"] = ...,
    nan_on_zero: bool = ...,
) -> Data: ...
def discrete_wavelet_transform(
    data: Data,
    wavelet: _DwtWavelet = ...,
    level: int | None = ...,
    mode: Literal[
        "zero",
        "constant",
        "symmetric",
        "periodic",
        "smooth",
        "periodization",
        "reflect",
        "antisymmetric",
        "antireflect",
    ] = ...,
) -> Data: ...
def spectrogram(
    data: Data,
    nperseg: int | None = ...,
    noverlap: int | None = ...,
    window: str = ...,
    scaling: str = ...,
) -> Data: ...

__all__ = [
    "BandPower",
    "ContinuousWaveletTransform",
    "Cordance",
    "DiscreteWaveletTransform",
    "Spectrogram",
    "band_power",
    "continuous_wavelet_transform",
    "cordance",
    "discrete_wavelet_transform",
    "spectrogram",
]
