# This file is auto-generated by scripts/gen_stubs.py — do not edit manually.
# Run `uv run python scripts/gen_stubs.py` to regenerate.

from collections.abc import Iterator as Iterator

import numpy as np

from ..data import Data as Data
from ._fourier_transform_surrogates import FourierTransformSurrogates as FourierTransformSurrogates

def fourier_transform_surrogates(
    data: Data,
    n_surrogates: int,
    multivariate: bool = ...,
    return_data: bool = ...,
    random_state: np.random.Generator | int | None = ...,
) -> Iterator[Data]: ...

__all__ = ["FourierTransformSurrogates", "fourier_transform_surrogates"]
